Update main_COPY_AND_RENAME.py with events
Schulich-Ignite/flare pull request #10
Opened 2021-02-17 21:54 UTC by anandp1

As far as I'm aware there are two ways to implement the keyboard and mouse events. I have one way commented and the other is not commented. 

Correct me if I'm wrong but from what I tested out the first way only works with each click (you can't hold up arrow key). However, the second way you can hold and move the rectangle. The same goes with the mouse actions, the first way you can click it and second you can hold the action.

I added some logic to it so you can't go off the screen but I don't think it is too complicated to understand so maybe keep it? Not sure.

2021-02-20 08:55 UTC, AlphaRLee requested changes
Please remove the additional features and keep this as a simple template for keyboard presses and mouse clicks. I personally prefer the second version.

Your example code is better suited for a different example file altogether while the `main_COPY_AND_RENAME.py` should be left as simple as possible

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +GREEN = (0, 255, 0)
Unnecessary for boilerplate

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +rect_color = WHITE
Unnecessary for boilerplate

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    mouses = pygame.mouse.get_pressed()
This variable name is confusing (I have multiple mice plugged in?) Consider using `mouse_buttons`

```suggestion
    mouse_buttons = pygame.mouse.get_pressed()
```

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    if(mouses[0]): # If left mouse pressed
PEP8 - don't add brackets around `if` statements unnecessarily and put two spaces between the end of your line and the start of a comment

```suggestion
    if mouses[0]:  # If left mouse pressed
```

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +        rect_y = mouse_pos[1]
Unnecessary for boilerplate

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    elif(mouses[2]): # If right mouse pressed
PEP8 - don't add brackets around if statements unnecessarily
```suggestion
    elif mouses[2]: # If right mouse pressed
```

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +        color = GREEN # Change colour to green
Unnecessary for boilerplate

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    """
Good as an example, not useful for boilerplate

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    pygame.draw.rect(screen, rect_color, (rect_x, rect_y, rect_width, rect_height))
Unnecessary for boilerplate

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +        rect_y += rect_speed # Going down
Strip down to just the boilerplate version
```suggestion
    if keys[pygame.K_UP]:
        ...  # Replace this line
    elif keys[pygame.K_LEFT]:
        ...  # Replace this line
    elif keys[pygame.K_RIGHT]:
        ...  # Replace this line
    elif keys[pygame.K_DOWN]:
        ...  # Replace this line
```

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    keys = pygame.key.get_pressed()
Consider renaming `keys` to `keys_pressed` to be more accurate
```suggestion
    keys_pressed = pygame.key.get_pressed()
```

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +            """
Probably safe to scrap this version; we can teach this on a need-to-know basis

2021-02-20 08:55 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    # The second way of interacting with events
This comment is unnecessary if we're only showing one version

2021-02-20 19:10 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +        # Replace this line
Python complains if you have empty blocks. You need to use the keyword `pass` (or its synonym `...`) to indicate "empty block"
```suggestion
    if keys_pressed[pygame.K_UP]:
        pass # Replace this line
    if keys_pressed[pygame.K_LEFT]:
        pass # Replace this line
    if keys_pressed[pygame.K_RIGHT]:
        pass # Replace this line
    if keys_pressed[pygame.K_DOWN]:
        pass # Replace this line
```

2021-02-20 19:12 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> -
Can you add this empty line again for consistency? We have 3 empty lines in each section

2021-02-20 19:12 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +    # Runs while you hold it
This comment doesn't help very much (we're not using version 1 anymore, so this is irrelevant)
```suggestion
```

2021-02-20 19:20 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> +        # Replace this line
1.  You can move `mouse_pos` above the entire `mouse_buttons` definition (because you can still use the mouse position without clicking). 
2. You can delete the comment `# Runs while you hold it` because it gives no value without your version 1 code
3. Also don't forget to add the `pass` keyword to your empty blocks
```suggestion
    # Mouse events
    mouse_pos = pygame.mouse.get_pos()  # Get position of mouse as a tuple representing the (x, y) coordinate
    mouse_buttons = pygame.mouse.get_pressed()
    if mouse_buttons[0]:  # If left mouse pressed
        pass  # Replace this line
    if mouse_buttons[2]:  # If right mouse pressed
        pass  # Replace this line
```

2021-02-21 00:11 UTC, joel-wong commented on main_COPY_AND_RENAME.py
> -
Generally we leave a newline at the end of every Python file

2021-02-21 00:58 UTC, AlphaRLee commented on main_COPY_AND_RENAME.py
> -
Good point. Once this is resolved, this file should be good to merge

2021-02-21 04:19 UTC, anandp1 commented on main_COPY_AND_RENAME.py
> -
Hmm, that's weird I had a new line in my file. I added an extra line and it seemed to fix the problem though.

2021-02-21 04:36 UTC, joel-wong commented on main_COPY_AND_RENAME.py
> -
Looks like there was some unneeded whitespace on the last line. Thanks for fixing it, Anand!

2021-02-21 04:37 UTC, AlphaRLee approved these changes
Looks good to me. Feel free to merge into main

2021-02-21 04:49 UTC, merged