Refactored platform class to use Pygame sprites
Schulich-Ignite/flare pull request #15
Opened 2021-03-06 10:42 UTC by AlphaRLee

2021-03-06 17:32 UTC, anandp1 commented on game/main.py
Not sure if this is relevant but the preview picture shows 4 platforms, but there are only 3 here. Might lead to some confusion?

2021-03-06 18:44 UTC, joel-wong requested changes
The implementation of the platform class looks good, just a few comments about how we could help students better understand the code and the changes

2021-03-06 18:44 UTC, joel-wong commented on game/README.md
> +We have updated the [platform.py](platform.py) file before this session started! The new `platform.py` is now a sprite with an image (be sure to also download and add the [platform_tile.png](assets/p
This sentence doesn't make sense to me:
`We have updated the [platform.py](platform.py) file before this session started!`

I prefer this wording:
`The [platform.py](platform.py) file was updated before this session started.`

This does not seem entirely correct either:
`The new platform.py is now a sprite with an image`
and I would suggest replacing it with
`The new Platform class in platform.py is now a sprite with an image`

Similarly:
`This platform.py sprite repeats the platform_tile.png image for any given width and height`
can be rewritten to
`The Platform sprite repeats the platform_tile.png image for any given width and height`

2021-03-06 18:44 UTC, joel-wong commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
Can you add a comment here to explain to students what is occurring?

2021-03-06 23:37 UTC, AlphaRLee commented on game/main.py
The picture was only for demonstration's sake for this PR (specifically demonstrating platforms less than 50 tall. It's unrelated to the actual game itself.

2021-03-06 23:56 UTC, AlphaRLee commented on game/main.py
Nvm, I decided to add the platform in the code as well to avoid any further confusion

2021-03-07 00:52 UTC, joel-wong requested changes

2021-03-07 00:52 UTC, joel-wong commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
Is there the possibility of one-off errors here?

2021-03-07 00:52 UTC, joel-wong commented on game/platform.py
> +        # We use list comprehension to quickly make the blits_data list of tuples (each tuple has the tile image, and the X and Y coordinates)
"list comprehension" is a bit of a technical term, can we explain it in more plan language?

2021-03-07 00:52 UTC, joel-wong commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
Can we split this into multiple lines for better readability?

2021-03-07 07:49 UTC, AlphaRLee commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
I'm going to need some clarification on what "one-off errors" you have in mind. What's the edge case you're considering?

2021-03-07 07:51 UTC, AlphaRLee commented on game/platform.py
> +        # We use list comprehension to quickly make the blits_data list of tuples (each tuple has the tile image, and the X and Y coordinates)
To avoid using the term "list comprehension" means to avoid using it altogether. I intentionally kept it in to motivate students to go google the term and learn it (this file works without any editing anyway, so if people choose to not do a little research then no harm done).

To any students reading this, learn to Google. It's the programmer's best friend 😉

2021-03-07 08:00 UTC, AlphaRLee commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
See comment above - this entire file wasn't prioritized to be readable; if we wanted that then we should have avoided trying to tile images in the first place. By providing this entire file, we're intentionally sidestepping a lot of topics
I intended the comments for:
* Understanding how to _use_ this class
* Motivating a little research and dropping some keyword hints for where to start

2021-03-07 15:56 UTC, joel-wong commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
Example:
width = 201
height = 50

In this case, there will be 5 tiles and the width will actually be 250.

Do we want to do round(width/tile_width) instead?

2021-03-07 16:14 UTC, joel-wong approved these changes
Looks good!

2021-03-07 19:00 UTC, AlphaRLee commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
Marking as resolved. As discussed in meetings, the pygame docs say that images blitted off the edge of the destination surface are simply cropped off, as intended. The docs are a bit vague because it only mentions the returned rectangle:
> The return rectangle is the area of the affected pixels, excluding any pixels outside the destination Surface, or outside the clipping area.

but testing shows that the image displayed is also cropped as intended

2021-03-07 19:01 UTC, merged

2021-03-07 20:04 UTC, joel-wong commented on game/platform.py
> +        blits_data = [(tile_image, (tile_width * i, 0)) for i in range(math.ceil(width / tile_width))]
Perfect, thanks for adding this comment!